openapi: 3.0.3
info:
  title: URL Shortener API
  version: 1.0.0
  description: |
    OpenAPI specification for the endpoints exposed by UrlShortnerController.
    
    This service allows creating a shortened URL for a given full URL and
    resolving a short code to the original URL via an HTTP redirect.
servers:
  - url: http://localhost:8080
paths:
  /v1/{id}:
    get:
      summary: Resolve short URL and redirect to the original URL
      description: |
        Looks up the given short URL id and issues a 301 redirect to the original URL.
        If the id does not exist, a 404 is returned.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Short URL identifier (base32-encoded string)
      responses:
        '301':
          description: Moved Permanently — Redirect to the original URL
          headers:
            Location:
              description: The original (long) URL
              schema:
                type: string
                format: uri
        '404':
          description: Not Found — No mapping for the given id
  /v1/:
    post:
      summary: Create a short URL for the provided URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UrlCreateRequest'
            examples:
              createShortUrl:
                summary: Sample request
                value:
                  url: https://example.com/some/long/path
      responses:
        '200':
          description: Short URL created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortUrlResponse'
              examples:
                success:
                  value:
                    shortUrl: http://localhost:8080/v1/GE2TKOBZGA2TAMBT
        '400':
          description: Bad Request — Validation failed for the provided URL
components:
  schemas:
    UrlCreateRequest:
      type: object
      properties:
        url:
          type: string
          format: uri
          description: The full URL to shorten
      required:
        - url
    ShortUrlResponse:
      type: object
      properties:
        shortUrl:
          type: string
          format: uri
          description: The fully-qualified shortened URL
      required:
        - shortUrl
